### ISSUE TITLE
Can not compile IMD-master

### ISSUE THREAD

**Issue by wesleybirdy1993** [fmqeisfeld/IMD#4]
Dear Professor, 
          Your IMD code not compilied, is that because MPICH2 was updated to MPICH3? How should can i do to run this IMD successfully?

**Comment by fmqeisfeld** [comment]
Hi wesleybirdy, unfortunately this package has no support for MPICH3. So the only options are either to downgrade to MPICH2 or to implement the neccessary adjustments. By the way, if you're not planning on doing laser-ablation simulations anyway, you can use the original IMD-package, which has support for MPICH3 at https://github.com/itapmd/imd/tree/master/src
